//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 10:02:22 AM CST 
//


package com.mastercard.api.partnerwallet.domain.partnerprovisioning;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UpdateWalletRequest_QNAME = new QName("", "UpdateWalletRequest");
    private final static QName _ShippingAddress_QNAME = new QName("", "ShippingAddress");
    private final static QName _RegisterWalletResponse_QNAME = new QName("", "RegisterWalletResponse");
    private final static QName _RewardProgram_QNAME = new QName("", "RewardProgram");
    private final static QName _ExtensionPoint_QNAME = new QName("", "ExtensionPoint");
    private final static QName _Profile_QNAME = new QName("", "Profile");
    private final static QName _Wallet_QNAME = new QName("", "Wallet");
    private final static QName _Errors_QNAME = new QName("", "Errors");
    private final static QName _Card_QNAME = new QName("", "Card");
    private final static QName _RegisterWalletRequest_QNAME = new QName("", "RegisterWalletRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link Card }
     * 
     */
    public Card createCard() {
        return new Card();
    }

    /**
     * Create an instance of {@link RegisterWalletRequest }
     * 
     */
    public RegisterWalletRequest createRegisterWalletRequest() {
        return new RegisterWalletRequest();
    }

    /**
     * Create an instance of {@link Wallet }
     * 
     */
    public Wallet createWallet() {
        return new Wallet();
    }

    /**
     * Create an instance of {@link ShippingAddress }
     * 
     */
    public ShippingAddress createShippingAddress() {
        return new ShippingAddress();
    }

    /**
     * Create an instance of {@link RegisterWalletResponse }
     * 
     */
    public RegisterWalletResponse createRegisterWalletResponse() {
        return new RegisterWalletResponse();
    }

    /**
     * Create an instance of {@link Errors }
     * 
     */
    public Errors createErrors() {
        return new Errors();
    }

    /**
     * Create an instance of {@link ExtensionPoint }
     * 
     */
    public ExtensionPoint createExtensionPoint() {
        return new ExtensionPoint();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link RewardProgram }
     * 
     */
    public RewardProgram createRewardProgram() {
        return new RewardProgram();
    }

    /**
     * Create an instance of {@link DateOfBirth }
     * 
     */
    public DateOfBirth createDateOfBirth() {
        return new DateOfBirth();
    }

    /**
     * Create an instance of {@link UpdateWalletRequest }
     * 
     */
    public UpdateWalletRequest createUpdateWalletRequest() {
        return new UpdateWalletRequest();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link java.lang.Error }
     * 
     */
    public java.lang.Error createError() {
        return new java.lang.Error();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link UpdateWalletRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UpdateWalletRequest")
    public JAXBElement<UpdateWalletRequest> createUpdateWalletRequest(UpdateWalletRequest value) {
        return new JAXBElement<UpdateWalletRequest>(_UpdateWalletRequest_QNAME, UpdateWalletRequest.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link ShippingAddress }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShippingAddress")
    public JAXBElement<ShippingAddress> createShippingAddress(ShippingAddress value) {
        return new JAXBElement<ShippingAddress>(_ShippingAddress_QNAME, ShippingAddress.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link RegisterWalletResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RegisterWalletResponse")
    public JAXBElement<RegisterWalletResponse> createRegisterWalletResponse(RegisterWalletResponse value) {
        return new JAXBElement<RegisterWalletResponse>(_RegisterWalletResponse_QNAME, RegisterWalletResponse.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link RewardProgram }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RewardProgram")
    public JAXBElement<RewardProgram> createRewardProgram(RewardProgram value) {
        return new JAXBElement<RewardProgram>(_RewardProgram_QNAME, RewardProgram.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link ExtensionPoint }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExtensionPoint")
    public JAXBElement<ExtensionPoint> createExtensionPoint(ExtensionPoint value) {
        return new JAXBElement<ExtensionPoint>(_ExtensionPoint_QNAME, ExtensionPoint.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link Profile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Profile")
    public JAXBElement<Profile> createProfile(Profile value) {
        return new JAXBElement<Profile>(_Profile_QNAME, Profile.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link Wallet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Wallet")
    public JAXBElement<Wallet> createWallet(Wallet value) {
        return new JAXBElement<Wallet>(_Wallet_QNAME, Wallet.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link Errors }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Errors")
    public JAXBElement<Errors> createErrors(Errors value) {
        return new JAXBElement<Errors>(_Errors_QNAME, Errors.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link Card }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Card")
    public JAXBElement<Card> createCard(Card value) {
        return new JAXBElement<Card>(_Card_QNAME, Card.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link RegisterWalletRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RegisterWalletRequest")
    public JAXBElement<RegisterWalletRequest> createRegisterWalletRequest(RegisterWalletRequest value) {
        return new JAXBElement<RegisterWalletRequest>(_RegisterWalletRequest_QNAME, RegisterWalletRequest.class, null, value);
    }

}
